### ISSUE TITLE
Intent: Update Example/Documentation

### ISSUE THREAD

**Issue by bronsonholden** [krainboltgreene/jsonapi-realizer.rb#7]
Just started using this gem, and am loving it so far. Using to update was a bit of a head-scratcher. Had to play around with a few things to get it working, since I couldn't find a test or anything in the README that showed an example of realizing with `intent: :update`.

Is this the approach you had in mind? Just want to make sure I'm not missing something with the API. Example is a Document resource with one attribute, name, that is being updated.

```
realizer = DocumentRealizer.new(intent: :update, parameters: params.require(:data).permit(:id), headers: request.headers)
realizer.object.update!(params.require(:data).permit(attributes: [:name]))
```

**Comment by krainboltgreene** [comment]
Holy shit I'm so happy and also so embarrassed!

**Comment by bronsonholden** [comment]
No worries! I eventually got my head around it when it clicked that it made no sense for the base Realizer to permit attributes, since the gem isn't Rails-exclusive, so it doesn't make sense for it to deal with the strong parameters shenanigans internally. I can just make a wrapper around it or permit the parameters in `initialize` for my base Realizer class.

**Comment by krainboltgreene** [comment]
Yes, okay so there are two things at play here:

1. Your confusion may be based on the fact that public facing documentation is for the up coming v6 (tagged v6.0.0-rc3, released if you want to try it).
2. Due to how JSON:API works, the gem has to figure out what to do for an individual request and while in rails you have the controller action, in most frameworks you only have the request verb. So we ask for that head of time!


Finally, if you don't know I also have two sister projects: jsonapi-materializer and jsonapi-home. Both are being worked on for a new major release, but I'd love your opinion if you get time.

**Comment by krainboltgreene** [comment]
Here's where it matters:

https://github.com/krainboltgreene/jsonapi-realizer.rb/blob/v6.0.0.rc3/lib/jsonapi/realizer/resource.rb#L83-L85
https://github.com/krainboltgreene/jsonapi-realizer.rb/blob/v6.0.0.rc3/lib/jsonapi/realizer/resource.rb#L230-L231

**Comment by bronsonholden** [comment]
Gotcha. Yeah I had to dive into the code (have to do this more often for Ruby projects than for any other language—not sure why).

jsonapi-materializer looks great too. I actually started off with jsonapi-serializers, but it's so easy to swap serialiazers out, I'll probably give yours a test drive too.

I'm really intrigued by [smart_params](https://github.com/krainboltgreene/smart_params.rb) though. These sorts of gems are really what I'm looking for, that do exactly what's needed and no more. Some of the popular Rails gems seem to force a lot of magic on you. "Opinionated" seems to be the red flag.
